version: '3.8'

services:
  jpms:
    image: ghcr.io/belphegorprime/jelly-public-music-share:latest
    container_name: jelly-public-music-share
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_USERNAME=${JELLYFIN_USERNAME}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - TOKEN_USAGE_LIMIT=${TOKEN_USAGE_LIMIT}
    volumes:
      - downloads:/public/songs
      # optinal tmp volume
      #- tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  downloads:
  #tmp: